### PR TITLE
Use a custom theme for Arduino IDE 2 [HC-1270]

### PR DESCRIPTION
**Pull request by gorillagripcore**

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
Since this is something that only advanced users should attempt, without expectation of support from Arduino for the 3rd party themes, we made a conscious decision that this information should only be published in the advanced usage documentation in the GitHub repository:

https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#3rd-party-themes

**Comment by gorillagripcore** [comment]
> Since this is something that only advanced users should attempt, without expectation of support from Arduino for the 3rd party themes, we made a conscious decision that this information should only be published in the advanced usage documentation in the GitHub repository:
> 
> https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#3rd-party-themes

I mean we already have this: https://support.arduino.cc/hc/en-us/articles/4408893497362-Use-a-custom-theme-for-Arduino-IDE-1

Also, how is it "something that only advanced users should attempt"? :)

**Comment by per1234** [comment]
>we already have this

Yes, but the custom themes for Arduino IDE 1.x are designed specifically for Arduino IDE 1.x. So there is a reasonable level of confidence that they will work correctly.

> how is it "something that only advanced users should attempt"?

Because these themes were created for VS Code, not for Arduino IDE. The Arduino IDE theme system is a bit convoluted and this means it is a gamble whether or not there will be sufficient contrast between foreground and background colors (even though the theme is perfect when used with VS Code). In some cases, this will make UI elements invisible.

We actually already have this problem with the themes that are built into the Eclipse Theia framework and thus are included in the IDE installation. This caused us to receive many bug reports and support requests from users of those themes until the Arduino IDE developers finally managed to find a way to remove those options from the IDE preferences to stop people from using them.

**Comment by gorillagripcore** [comment]
@per1234 You can literally just change back to a default theme if it doesn't work. it's not that deep. 

I can put a warning in the article if you want :))

**Comment by per1234** [comment]
The average user won't understand that the apparently missing UI element is caused by the theme. They will think it is caused by a bug in the IDE. And so it becomes a burden on those of us who provide support and maintainership for the Arduino IDE 2.x. We are already stretched far too thin so we don't need any more.

I'm sorry but this was already decided 1.5 years ago. It is not worth discussing any further.

**Comment by seaxwi** [comment]
Hi @per1234

> Since this is something that only advanced users should attempt, without expectation of support from Arduino for the 3rd party themes, we made a conscious decision that this information should only be published in the advanced usage documentation in the GitHub repository

I was not aware of this decision, although given the points you raised I can understand why it was made.

> we made a conscious decision that this information should only be published in the advanced usage documentation in the GitHub repository

Does this decision also mean we should avoid linking to the information from more accessible documentation sources like the Help Center? For example, linking to it from [the existing custom theme installation article](https://support.arduino.cc/hc/en-us/articles/4408893497362-Use-a-custom-theme-for-Arduino-IDE-1), while mentioning the limitations of using themes designed for VS Code and that it is not a supported feature?

**Pull request closed without merging**
